[package]
name = "cjump-plus"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.22.0"
egui = "0.22.0"
mki = "0.2.3"
serde = "1.0.171"
toml = "0.7.6"
